GET http://localhost:5000/


###

POST http://localhost:5000/auth/signup/

{
    "firstname": "Obi",
    "lastname": "Chidubem",
    "email": "testemail@blog.com",
    "password": "testpassword"
}
